# Generated by Django 5.2.8 on 2026-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0002_cours_fichiersource_partie_chapitre_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
