# Generated by Django 5.2.8 on 2026-01-25 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0003_alter_utilisateur_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code du template')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_notification', models.CharField(choices=[('DOCUMENT_TRAITE', 'Document traité'), ('DOCUMENT_ERREUR', 'Erreur de traitement'), ('NOUVELLE_EVALUATION', 'Nouvelle évaluation'), ('EVALUATION_CORRIGEE', 'Évaluation corrigée'), ('NOUVEAU_MESSAGE', 'Nouveau message'), ('SYSTEM_MAINTENANCE', 'Maintenance système'), ('PROFIL_MIS_A_JOUR', 'Profil mis à jour'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de notification')),
                ('template_email_sujet', models.CharField(max_length=200, verbose_name='Sujet email')),
                ('template_email_html', models.TextField(verbose_name='Template email HTML')),
                ('template_email_text', models.TextField(verbose_name='Template email texte')),
                ('template_push_titre', models.CharField(max_length=100, verbose_name='Titre push')),
                ('template_push_message', models.TextField(verbose_name='Message push')),
                ('template_in_app_titre', models.CharField(max_length=100, verbose_name='Titre in-app')),
                ('template_in_app_message', models.TextField(verbose_name='Message in-app')),
                ('variables_disponibles', models.JSONField(default=list, help_text='Liste des variables disponibles dans le template', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notification',
                'db_table': 'xcsm_notification_template',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('DOCUMENT_TRAITE', 'Document traité'), ('DOCUMENT_ERREUR', 'Erreur de traitement'), ('NOUVELLE_EVALUATION', 'Nouvelle évaluation'), ('EVALUATION_CORRIGEE', 'Évaluation corrigée'), ('NOUVEAU_MESSAGE', 'Nouveau message'), ('SYSTEM_MAINTENANCE', 'Maintenance système'), ('PROFIL_MIS_A_JOUR', 'Profil mis à jour'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON (ex: IDs des objets concernés)', verbose_name='Métadonnées')),
                ('est_vue', models.CharField(choices=[('NON_VUE', 'Non vue'), ('VUE', 'Vue'), ('ARCHIVEE', 'Archivée')], default='NON_VUE', max_length=20, verbose_name='État')),
                ('envoyee_email', models.BooleanField(default=False, verbose_name='Envoyée par email')),
                ('envoyee_push', models.BooleanField(default=False, verbose_name='Envoyée par push')),
                ('envoyee_in_app', models.BooleanField(default=True, verbose_name='Disponible in-app')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_archivage', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('email_message_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID du message email')),
                ('email_statut', models.CharField(blank=True, choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('OUVERT', 'Ouvert'), ('CLIQUE', 'Cliqué')], max_length=50, null=True, verbose_name='Statut email')),
                ('push_message_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID du message push')),
                ('push_statut', models.CharField(blank=True, choices=[('ENVOYE', 'Envoyé'), ('RECU', 'Reçu'), ('OUVERT', 'Ouvert'), ('ECHEC', 'Échec')], max_length=50, null=True, verbose_name='Statut push')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='xcsm.cours')),
                ('fichier_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='xcsm.fichiersource')),
                ('granule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='xcsm.granule')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'xcsm_notification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu_html', models.TextField(verbose_name='Contenu HTML')),
                ('contenu_text', models.TextField(verbose_name='Contenu texte')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('OUVERT', 'Ouvert')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('email_message_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID du message email')),
                ('email_ouvert', models.BooleanField(default=False, verbose_name='Email ouvert')),
                ('email_clique', models.BooleanField(default=False, verbose_name='Email cliqué')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_ouverture', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('date_clic', models.DateTimeField(blank=True, null=True, verbose_name='Date de clic')),
                ('notifications', models.ManyToManyField(related_name='digests', to='xcsm.notification', verbose_name='Notifications incluses')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synthèse de notifications',
                'verbose_name_plural': 'Synthèses de notifications',
                'db_table': 'xcsm_notification_digest',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_traite_email', models.BooleanField(default=True, verbose_name='Document traité - Email')),
                ('document_traite_push', models.BooleanField(default=False, verbose_name='Document traité - Push')),
                ('document_traite_in_app', models.BooleanField(default=True, verbose_name='Document traité - In-App')),
                ('document_erreur_email', models.BooleanField(default=True, verbose_name='Erreur traitement - Email')),
                ('document_erreur_push', models.BooleanField(default=True, verbose_name='Erreur traitement - Push')),
                ('document_erreur_in_app', models.BooleanField(default=True, verbose_name='Erreur traitement - In-App')),
                ('nouvelle_evaluation_email', models.BooleanField(default=True, verbose_name='Nouvelle évaluation - Email')),
                ('nouvelle_evaluation_push', models.BooleanField(default=True, verbose_name='Nouvelle évaluation - Push')),
                ('nouvelle_evaluation_in_app', models.BooleanField(default=True, verbose_name='Nouvelle évaluation - In-App')),
                ('evaluation_corrigee_email', models.BooleanField(default=True, verbose_name='Évaluation corrigée - Email')),
                ('evaluation_corrigee_push', models.BooleanField(default=False, verbose_name='Évaluation corrigée - Push')),
                ('evaluation_corrigee_in_app', models.BooleanField(default=True, verbose_name='Évaluation corrigée - In-App')),
                ('nouveau_message_email', models.BooleanField(default=False, verbose_name='Nouveau message - Email')),
                ('nouveau_message_push', models.BooleanField(default=True, verbose_name='Nouveau message - Push')),
                ('nouveau_message_in_app', models.BooleanField(default=True, verbose_name='Nouveau message - In-App')),
                ('system_maintenance_email', models.BooleanField(default=True, verbose_name='Maintenance système - Email')),
                ('system_maintenance_push', models.BooleanField(default=True, verbose_name='Maintenance système - Push')),
                ('system_maintenance_in_app', models.BooleanField(default=True, verbose_name='Maintenance système - In-App')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications email activées')),
                ('push_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications push activées')),
                ('in_app_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications in-app activées')),
                ('digest_frequency', models.IntegerField(choices=[(0, 'Jamais'), (6, 'Toutes les 6 heures'), (12, 'Toutes les 12 heures'), (24, 'Quotidien'), (168, 'Hebdomadaire')], default=24, verbose_name='Fréquence des emails de synthèse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'xcsm_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('WEB', 'Navigateur web'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('OTHER', 'Autre')], max_length=20, verbose_name="Type d'appareil")),
                ('device_id', models.CharField(help_text="Identifiant unique de l'appareil", max_length=500, unique=True, verbose_name="ID de l'appareil")),
                ('device_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'appareil")),
                ('device_model', models.CharField(blank=True, max_length=200, null=True, verbose_name="Modèle de l'appareil")),
                ('subscription_data', models.JSONField(help_text="Données d'abonnement au format spécifique au device", verbose_name="Données d'abonnement")),
                ('vapid_public_key', models.TextField(blank=True, null=True, verbose_name='Clé publique VAPID')),
                ('vapid_private_key', models.TextField(blank=True, null=True, verbose_name='Clé privée VAPID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Dernière connexion')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_desactivation', models.DateTimeField(blank=True, null=True, verbose_name='Date de désactivation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'db_table': 'xcsm_push_subscription',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'est_vue', 'date_creation'], name='xcsm_notifi_utilisa_405854_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification', 'date_creation'], name='xcsm_notifi_type_no_aa99e8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['fichier_source'], name='xcsm_notifi_fichier_674312_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['cours'], name='xcsm_notifi_cours_i_f8d0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['utilisateur', 'is_active'], name='xcsm_push_s_utilisa_890f26_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['device_type', 'is_active'], name='xcsm_push_s_device__0066d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('utilisateur', 'device_id')},
        ),
    ]
