# Generated by Django 5.2.8 on 2026-01-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0005_actionlog_evaluation_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='filiere',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='L1', max_length=10),
        ),
    ]
